# 1 HMM

## 1.1 评估与推断问题

In [1]:
import HMM
import numpy as np
np.random.seed(29)
A, E, Pi, O, Q, V = HMM.model_example()
HMM.run_evaluation_decoding(A, E, Pi, O, Q, V)

**********************************************模型的评估问题***********************************************
***********************前向算法***********************
(0.130218, array([[0.1     , 0.16    , 0.28    ],
       [0.077   , 0.1104  , 0.0606  ],
       [0.04187 , 0.035512, 0.052836]]))
***********************后向算法***********************
(0.130218, array([[0.2451, 0.2622, 0.2277],
       [0.54  , 0.49  , 0.57  ],
       [1.    , 1.    , 1.    ]]))
**********************************************隐状态推断问题***********************************************
(0.014699999999999998, array([3., 3., 3.]))


## 1.2 模型学习问题

In [2]:
import HMM
import numpy as np
np.random.seed(29)
n = 100
iter_times = 200
A, E, Pi, Q, V = HMM.model_example2()
HMM.run_learning(A, E, Pi, Q, V, n, iter_times)

**********************************************模型的学习问题***********************************************
*********************知道隐状态序列**********************
状态转移矩阵A估计差值: 
 [[ 0.    0.    0.  ]
 [-0.07  0.    0.07]
 [ 0.02 -0.02  0.  ]]
发射概率矩阵E估计差值: 
 [[ 0.03 -0.03]
 [ 0.    0.  ]
 [ 0.04 -0.04]]
*********************不知道隐状态序列*********************
状态转移矩阵A估计差值: 
 [[-0.    0.   -0.  ]
 [ 0.05 -0.   -0.05]
 [ 0.04 -0.04 -0.  ]]
发射概率矩阵E估计差值: 
 [[ 0.09 -0.09]
 [ 0.   -0.  ]
 [-0.07  0.07]]
发射概率矩阵Pi估计差值: 
 [-0.  0. -0.]
